//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/VRRig/InputActions/VRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRInputActions"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""6c02b9df-4ee3-4df4-b0fd-3997afa6234d"",
            ""actions"": [
                {
                    ""name"": ""LFlipper"",
                    ""type"": ""Value"",
                    ""id"": ""89ab98da-77e3-4950-bc7f-9f1f03a9314d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RFlipper"",
                    ""type"": ""Value"",
                    ""id"": ""34095f93-f875-4463-864b-4349cef81a19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Plunger"",
                    ""type"": ""Button"",
                    ""id"": ""075cb102-f564-4486-8250-7dd73bd7ae35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""223de6f9-8abd-462b-8100-d75180030698"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""2439f92b-2cf9-4ad2-a0d4-ec0271592764"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""1046e562-b248-4c21-bb16-a83f3f9528b0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""caec04b3-edfd-4ee7-8ac6-83e501dc891e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightGripPressed"",
                    ""type"": ""Value"",
                    ""id"": ""aeee339d-312b-455e-9258-5e01376dcd50"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftGripPressed"",
                    ""type"": ""Value"",
                    ""id"": ""6879e91d-51ba-456b-89da-4c25548c6b5b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightPrimary_Button"",
                    ""type"": ""Button"",
                    ""id"": ""9379b8e2-e4c9-4c47-a37f-2a94b79aaadb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPrimary_Button"",
                    ""type"": ""Button"",
                    ""id"": ""f6867d17-017f-4de9-acf5-86300c73dc84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b270f028-a9b4-4ac6-bb79-02edda748ea4"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""K&M"",
                    ""action"": ""LFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99085299-0805-466d-816d-b01ff5b9f0f7"",
                    ""path"": ""<OculusTouchController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""LFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52f4435b-b87b-4fbc-9b2f-ed34cd89498a"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""K&M"",
                    ""action"": ""RFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5423ec89-bc23-498a-a978-371d10c158db"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""RFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b39d4ee-caa9-461c-b330-a6166f2a2c35"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""K&M"",
                    ""action"": ""Plunger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ce401e-7572-4834-9a77-42c78947a98e"",
                    ""path"": ""<OculusTouchController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""Plunger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""153621e5-13a9-4a3a-b20c-3a565e935cd2"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be033f1-7394-444d-9f77-e2bb4d066dac"",
                    ""path"": ""<OculusTouchController>/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d00a5c5f-0889-481a-9eea-332b3e382051"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59c28c28-1597-4647-9829-cc390b381e8d"",
                    ""path"": ""<OculusTouchController>/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20447b5d-18bf-4e98-b3f0-618079248b1f"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""RightGripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd11aca3-4867-46cb-b54d-81f50e5005a5"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""LeftGripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dbc3abd-72aa-4a7c-b30e-a05441ab1c11"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""RightPrimary_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74f08699-cf7e-4160-9639-605fb4b6c1e8"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""LeftPrimary_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""K&M"",
            ""bindingGroup"": ""K&M"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""VR"",
            ""bindingGroup"": ""VR"",
            ""devices"": [
                {
                    ""devicePath"": ""<OpenXRHmd>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<OculusTouchController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<OculusTouchController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_LFlipper = m_Default.FindAction("LFlipper", throwIfNotFound: true);
        m_Default_RFlipper = m_Default.FindAction("RFlipper", throwIfNotFound: true);
        m_Default_Plunger = m_Default.FindAction("Plunger", throwIfNotFound: true);
        m_Default_LeftJoystick = m_Default.FindAction("LeftJoystick", throwIfNotFound: true);
        m_Default_RightJoystick = m_Default.FindAction("RightJoystick", throwIfNotFound: true);
        m_Default_RightTrigger = m_Default.FindAction("RightTrigger", throwIfNotFound: true);
        m_Default_Trigger = m_Default.FindAction("Trigger", throwIfNotFound: true);
        m_Default_RightGripPressed = m_Default.FindAction("RightGripPressed", throwIfNotFound: true);
        m_Default_LeftGripPressed = m_Default.FindAction("LeftGripPressed", throwIfNotFound: true);
        m_Default_RightPrimary_Button = m_Default.FindAction("RightPrimary_Button", throwIfNotFound: true);
        m_Default_LeftPrimary_Button = m_Default.FindAction("LeftPrimary_Button", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_LFlipper;
    private readonly InputAction m_Default_RFlipper;
    private readonly InputAction m_Default_Plunger;
    private readonly InputAction m_Default_LeftJoystick;
    private readonly InputAction m_Default_RightJoystick;
    private readonly InputAction m_Default_RightTrigger;
    private readonly InputAction m_Default_Trigger;
    private readonly InputAction m_Default_RightGripPressed;
    private readonly InputAction m_Default_LeftGripPressed;
    private readonly InputAction m_Default_RightPrimary_Button;
    private readonly InputAction m_Default_LeftPrimary_Button;
    public struct DefaultActions
    {
        private @VRInputActions m_Wrapper;
        public DefaultActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LFlipper => m_Wrapper.m_Default_LFlipper;
        public InputAction @RFlipper => m_Wrapper.m_Default_RFlipper;
        public InputAction @Plunger => m_Wrapper.m_Default_Plunger;
        public InputAction @LeftJoystick => m_Wrapper.m_Default_LeftJoystick;
        public InputAction @RightJoystick => m_Wrapper.m_Default_RightJoystick;
        public InputAction @RightTrigger => m_Wrapper.m_Default_RightTrigger;
        public InputAction @Trigger => m_Wrapper.m_Default_Trigger;
        public InputAction @RightGripPressed => m_Wrapper.m_Default_RightGripPressed;
        public InputAction @LeftGripPressed => m_Wrapper.m_Default_LeftGripPressed;
        public InputAction @RightPrimary_Button => m_Wrapper.m_Default_RightPrimary_Button;
        public InputAction @LeftPrimary_Button => m_Wrapper.m_Default_LeftPrimary_Button;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @LFlipper.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLFlipper;
                @LFlipper.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLFlipper;
                @LFlipper.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLFlipper;
                @RFlipper.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRFlipper;
                @RFlipper.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRFlipper;
                @RFlipper.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRFlipper;
                @Plunger.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPlunger;
                @Plunger.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPlunger;
                @Plunger.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPlunger;
                @LeftJoystick.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftJoystick;
                @LeftJoystick.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftJoystick;
                @LeftJoystick.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftJoystick;
                @RightJoystick.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightJoystick;
                @RightJoystick.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightJoystick;
                @RightJoystick.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightJoystick;
                @RightTrigger.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightTrigger;
                @RightTrigger.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightTrigger;
                @RightTrigger.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightTrigger;
                @Trigger.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnTrigger;
                @Trigger.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnTrigger;
                @Trigger.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnTrigger;
                @RightGripPressed.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightGripPressed;
                @RightGripPressed.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightGripPressed;
                @RightGripPressed.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightGripPressed;
                @LeftGripPressed.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftGripPressed;
                @LeftGripPressed.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftGripPressed;
                @LeftGripPressed.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftGripPressed;
                @RightPrimary_Button.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightPrimary_Button;
                @RightPrimary_Button.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightPrimary_Button;
                @RightPrimary_Button.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRightPrimary_Button;
                @LeftPrimary_Button.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftPrimary_Button;
                @LeftPrimary_Button.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftPrimary_Button;
                @LeftPrimary_Button.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLeftPrimary_Button;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LFlipper.started += instance.OnLFlipper;
                @LFlipper.performed += instance.OnLFlipper;
                @LFlipper.canceled += instance.OnLFlipper;
                @RFlipper.started += instance.OnRFlipper;
                @RFlipper.performed += instance.OnRFlipper;
                @RFlipper.canceled += instance.OnRFlipper;
                @Plunger.started += instance.OnPlunger;
                @Plunger.performed += instance.OnPlunger;
                @Plunger.canceled += instance.OnPlunger;
                @LeftJoystick.started += instance.OnLeftJoystick;
                @LeftJoystick.performed += instance.OnLeftJoystick;
                @LeftJoystick.canceled += instance.OnLeftJoystick;
                @RightJoystick.started += instance.OnRightJoystick;
                @RightJoystick.performed += instance.OnRightJoystick;
                @RightJoystick.canceled += instance.OnRightJoystick;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @Trigger.started += instance.OnTrigger;
                @Trigger.performed += instance.OnTrigger;
                @Trigger.canceled += instance.OnTrigger;
                @RightGripPressed.started += instance.OnRightGripPressed;
                @RightGripPressed.performed += instance.OnRightGripPressed;
                @RightGripPressed.canceled += instance.OnRightGripPressed;
                @LeftGripPressed.started += instance.OnLeftGripPressed;
                @LeftGripPressed.performed += instance.OnLeftGripPressed;
                @LeftGripPressed.canceled += instance.OnLeftGripPressed;
                @RightPrimary_Button.started += instance.OnRightPrimary_Button;
                @RightPrimary_Button.performed += instance.OnRightPrimary_Button;
                @RightPrimary_Button.canceled += instance.OnRightPrimary_Button;
                @LeftPrimary_Button.started += instance.OnLeftPrimary_Button;
                @LeftPrimary_Button.performed += instance.OnLeftPrimary_Button;
                @LeftPrimary_Button.canceled += instance.OnLeftPrimary_Button;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    private int m_KMSchemeIndex = -1;
    public InputControlScheme KMScheme
    {
        get
        {
            if (m_KMSchemeIndex == -1) m_KMSchemeIndex = asset.FindControlSchemeIndex("K&M");
            return asset.controlSchemes[m_KMSchemeIndex];
        }
    }
    private int m_VRSchemeIndex = -1;
    public InputControlScheme VRScheme
    {
        get
        {
            if (m_VRSchemeIndex == -1) m_VRSchemeIndex = asset.FindControlSchemeIndex("VR");
            return asset.controlSchemes[m_VRSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnLFlipper(InputAction.CallbackContext context);
        void OnRFlipper(InputAction.CallbackContext context);
        void OnPlunger(InputAction.CallbackContext context);
        void OnLeftJoystick(InputAction.CallbackContext context);
        void OnRightJoystick(InputAction.CallbackContext context);
        void OnRightTrigger(InputAction.CallbackContext context);
        void OnTrigger(InputAction.CallbackContext context);
        void OnRightGripPressed(InputAction.CallbackContext context);
        void OnLeftGripPressed(InputAction.CallbackContext context);
        void OnRightPrimary_Button(InputAction.CallbackContext context);
        void OnLeftPrimary_Button(InputAction.CallbackContext context);
    }
}
